Use `expr_form` instead of `tgt_type` until we update salt
This is producing an error on our current salt version:

  `Rendering SLS 'base:cleanup.remove-post-orchestration' failed: Jinja error: get()
   got an unexpected keyword argument 'tgt_type'`

Go back to using `expr_form` until we update.

feature#deployment-stability