PCRE grain expressions only allow the regexp on the value side.
Fix PCRE grain query expressions so they are matching what we expect.

```
caasp-admin:~ # docker exec -it 06bf salt -P 'bootstrap_complete:.*' cmd.run hostname
admin:
    caasp-admin
6b5cb85d20f94f6eb813449b228cfe13:
    caasp-worker-1
4c0e4d31bc754369940ffcbae28e2f0a:
    caasp-worker-0
cb92123fa85d4170807e0aa24573501b:
    caasp-master-0
66d5844bc5f14d1480896b1bc234dd92:
    caasp-master-1
3f3f505c6eb3464e8a08cc0ae6fbc8f4:
    caasp-master-2
caasp-admin:~ # docker exec -it 06bf salt -P 'bootstrap_.*:true' cmd.run hostname
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```